//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int RentID { get; set; }
        public int UserID { get; set; }
        public int CarID { get; set; }
        public Nullable<int> RentPeriod { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Users Users { get; set; }
    }
}
